### ISSUE TITLE
Course description 

### ISSUE THREAD

**Issue by pmcmahon02** [WEB290-2015/webdevcapstone#13]
# Finalize remaining courses with description and content.  For courses that have no description listed on JCCC Class search, work with Mr. Hopper to develop a summary of course to provide user with valid overview.

**Comment by jhopper** [comment]
## WEB Course Descriptions

### Web 110 HTMl and CSS

This course will cover the essential skills needed to create websites, with a focus on using Hypertext Markup Language (HTML) and Cascading Style Sheets (CSS). Students will be introduced to the concepts, foundations, syntax and structure of HTML.  Additional topics include the use of File Transfer Protocol (FTP) to publish websites and validation to Web standards established by the World Wide Web Consortium (W3C) and other organizations. 3 hrs lecture/wk.

### WEB 112 Professional Skills for the Digital Developer

Upon successful completion of this course, the student will be able to demonstrate effective communications and professional skills important to a career in digital development. Topics covered include the use of technology to achieve effective written and verbal communication skills, team management, project management, and problem solving skills. Current and relevant legal, ethical, and governmental issues important to a career in digital development are also covered. 3 hrs. lecture/wk.

### WEB 114 Web Scripting JavaScript I

This course provides a foundation to client-side scripting using the JavaScript language.  Students will write, validate and debug JavaScript code to enhance the functionality of Web pages. Topics to be covered include common applications such as responding to user actions, creating pop-up dialog boxes and controlling the Web browser.  Students will apply JavaScript to manipulate and validate web form elements and data and to build menus and navigational structures.  2 hrs. lecture/wk.

### WEB 116 Digital Media Concepts

This course examines the digital media creation process and the impact of emerging technology on that process. Emphasis is placed on the need to understand target audiences, as well as the impact of content on those audiences. Creative culture is examined so students may begin to understand the relationship between ideas and the structure and management of the organizations and intellectual property systems used to express those ideas. 2 hrs. lecture/wk.

### WEB 121 Digital Media Assets

This course focuses on technologies and workflows in managing digital image, digital video and audio assets throughout an asset’s lifecycle. Through the study of digital and interactive media and its application in information technology, students will analyze and assess current and emerging technologies, while designing and creating multimedia projects that address customer needs and solve real world problems. Students implement personal and interpersonal skills to prepare for a rapidly evolving workplace environment. The knowledge and skills acquired and practiced will enable students to successfully perform and interact in a technology-driven society. 3 hrs. lecture/wk. 2 hrs open lab/wk.

### WEB 123 CMS Strategies

This course will cover the basics of installing and configuring a Web Content 
Management System (CMS) to build blogs and web sites. Students will use the CMS to perform many functions including installing plug-ins and assigning user permissions. 1 hour lecture/wk

### WEB 124 Web Scripting JavaScript II

Students apply JavaScript to manage state information, cookies and security. Students will also study the elements of a basic Asynchronous JavaScript and eXtensible Markup Language (AJAX) application. Students will learn advanced debugging techniques and apply their comprehensive JavaScript skills to a capstone case. 2 hrs. lecture/wk.

### Web 125 Digital Video Tools: Premiere

An introductory course for Video Production Technology students covering basic desktop computer operating systems and the technologies used to bring photographic (film, video, still) images and audio into the digital domain. Students will learn to prepare audio and video media from pre-production to post-production for digital delivery systems and the Internet. 1hr. lecture/wk

### WEB 126 Technical Interface Skills

This course will cover the skills needed to successfully develop Information Architecture (IA) blueprints from concept to completion. Students will use fundamental visual principles, perception, color, composition and typography to analyze and modify existing IA plans while keeping consistent structure. They will create complementary visuals that maintain a client’s brand while working through the modification process. Students will review the critical universal usability rules and basic visual design principles quintessential of a design team and to implement an aesthetic vision through every step of development. 3 hrs. lecture/wk.

### WEB 128 Server-Side Scripting PHP & MySQL

This course covers the commands and techniques available to add functionality to web pages using Hypertext Preprocessor (PHP).  Students will build client-side PHP scripts with variables, functions, expressions, methods and events to validate forms and enhance web page functionality. The basics of server-side scripting are introduced. Students also define and build a relational database using MySQL, then use PHP scripts as well as SQL in a web page to connect to the database to edit, delete and enter records.2 hr. lecture/wk

### WEB 150 Essential Web Concepts and Techniques I

This current-events course introduces students to essential Web concepts and techniques. Students will explore a range of topics, from fundamental existing technologies to new trends. Real-world applications of the Web will be the primary focus of this course. Hands-on, practical projects will be performed to reinforce the concepts. 1 hr. lecture/wk.

### WEB 152 Web Pages: Expression I

This course will cover the commands and techniques required to create and revise web pages using Expression Web. Topics to be covered will include researching, planning, and creating a web site, identifying the purpose of Hypertext Markup Language (HTML) and Cascading Style Sheets (CSS), inserting background color, inserting and editing images, creating lists, creating and applying style sheets, inserting files, creating internal and external links and publishing a web site. 1 hr. lecture/wk.

### WEB 154 Web pages: Dreamweaver I

This course will cover the commands and techniques required to create and revise Web pages using Dreamweaver. Topics to be covered will include basic text layout, viewing and identifying basic HTML tags, creating a site map, formatting a Web page, applying background color, inserting images and sounds, creating ordered and unordered lists, inserting files, and creating links on Web pages. 1 hr. lecture/wk.

### WEB 156 JavaScript I

This course provides a foundation to client-side scripting using the JavaScript language.  Students will write, validate and debug JavaScript code to enhance the functionality of Web pages. Topics to be covered include common applications such as responding to user actions, creating pop-up dialog boxes and controlling the Web browser. 1 hr lecture/wk.

### WEB 158 Adobe Flash I.

This course will cover the commands and techniques available to add Flash content to Web pages and CD-ROMs. Topics covered will include using drawing tools, manipulating text with text tools, adding and modifying sound, creating animation and publishing work. This class will be taught in a classroom with both Macintosh and Windows computers. 1 hr. lecture/wk.

### WEB 160 Essential Web Concepts and Techniques II

This course is a continuation of CWEB 150, Essential Web Concepts and Techniques, and will cover intermediate commands and techniques required to use various Web-based tools and programs. Students will explore a wide range of topics, from existing technologies to new trends. Real-world applications of the Web will be the primary focus of this course. Hands-on, practical projects will be performed to reinforce the concepts. 1 hr. lecture/wk.

### WEB 162 Web Pages: Expression II

This course is a continuation of WEB 152, Web Pages: Expression Web I, and will cover intermediate-level commands and techniques required to create and enhance web sites using Expression Web. Topics to be covered will include creating and modifying dynamic links, working with tables, creating forms, and using templates to design web pages. 1 hr. lecture/wk.

### WEB 164 Web pages: Dreamweaver II

Web Pages: Dreamweaver II builds upon the concepts and design techniques presented in the previous Dreamweaver course. The course includes a range of intermediate Dreamweaver techniques required to work efficiently and create manageable web site designs using Dreamweaver forms, Templates and Libraries, as well as covering managing your web site and checking files. 1 hr. lecture/wk. This course may be offered as a Learning Communities (LCOM) section, see current credit schedule for LCOM details.

### WEB 166 JavaScript I

This course builds on foundational JavaScript skills learned in CWEB 160. Students will apply JavaScript to manipulate and validate web form elements and data.  Students will learn to use JavaScript in their web pages to build menus and navigational structures.  Students will expand their debugging skills.  1 hr. lecture/wk

### WEB 168 Adobe Flash II

This course will build on the fundamental skills learned in Flash I. Topics will include complex animation techniques; interactivity with simple frame actions; and interactivity using objects such as buttons, hot spots and movie clips. 1 hr. lecture/wk.

### WEB 170 Podcasting

Podcasting is a web-based broadcast medium. Audio files (most commonly in MP3 format) are made available online in a way that allows software to automatically detect the availability of new files through various syndication technologies and download the files for listening at the user's convenience. This course will cover how to create sound, use the appropriate software, develop a show, distribute a podcast, and build an audience. Students will begin by learning the basics of blogging and develop their blogs into audio and/or video podcasts. More advanced topics include audio editing, podcasting on the go, and videocasting. 3 hrs. lecture/wk.

### WEB 172 Wordpress I

This course will cover the commands and techniques required to create and revise blogs and web sites using WordPress. Topics to be covered will include basic blogging techniques, working with digital images, hosting, spam and security issues, plugins and themes. Real-world applications of WordPress will be the primary focus of this course. Hands-on, practical projects will be performed to reinforce the concepts. 1 hr. lecture/wk.

### WEB 178 Adobe Flash III

This course will build on the skills learned in Flash II. Students will do projects to control movie clips, sound, external data, multiple timelines and text fields. Some ActionScripting will be introduced.  1 hr. lecture/wk.

### WEB 190 E-Commerce I

This course will introduce students to e-commerce in a software-driven, hands-on way. It will use software tools to discuss and explore a variety of e-commerce activities. Students will examine an extensive list of e-commerce sites, such as those that support purchasing, delivery, support, auction, business-to-business, virtual community and Web-portal business goals. They will examine e-commerce stores that incorporate advertising, marketing, branding, and business efficiency goals. They will explore how to populate a store catalog, create site-wide navigation links and publish a store. 1 hr. lecture/wk.

### WEB 192 E-Commerce II

Students will examine e-commerce security issues including privacy, copyright, and transaction integrity. Students will study electronic payment systems,  international, legal, and taxation issues. 1 hr. lecture/wk.

### WEB 230 Asynchronous JavaScript and XML

This course will introduce and explain the use of AJAX (Asynchronous JavaScript and eXtensible Markup Language). AJAX is not a technology itself but is a combination of HTML(Hypertext Markup Language), CSS(Cascading Style Sheets) and JavaScript's use of the DOM (Document Object Model). Students will use AJAX to dynamically load data into a Web page. Topics include auto complete functionality and other interactive features to a Web page. 1 hr. lecture/wk.

### WEB 231 Experience Design

This course will serve as a broad survey of the user experience design process for interactive products and services. Students will learn the building blocks of the user experience including interaction design, design research, information architecture and design principles. In addition to understanding how to discover needs and fulfill them with design, it will also provide knowledge of how to evaluate the concepts using common methods such as heuristic evaluation, prototyping or usability studies. Through readings, critiques, exercises and discussions, students will explore what makes the experience of an interactive media application successful. 3 hrs. lecture, 2 hrs. open lab/wk.

### WEB 232 XML

This course will introduce and explain the use of XML (eXtensible Markup Language) documents to encapsulate and transfer data across the Internet. Students will learn to use document type definitions, attributes and entities, and XML schemas to build valid and useful XML documents. CSS(Cascading Style Sheets) will be introduced to format the XML documents. JavaScript will be used to incorporate programming instructions into the XML document. 3 hrs. lecture/wk.

### WEB 233 Visual Storytelling

Storytelling is how people share ideas and meaning. It’s how we communicate, reach each other, and connect. This course provides an introduction to the methods and tools of visual storytelling.  Students will explore the impact of visual storytelling and how to communicate visually. Students will use storytelling techniques enabling them to create, design and produce stories using digital media. This course will explore the key elements to tell realistic and compelling visual stories.  Students write and storyboard narratives, create still and moving images using music and narration to tell their stories. Recommended prior courses are Fundamentals of Photography and Introduction to Photoshop.  6 hrs. integrated lecture, studio/wk.

### WEB 235 Digital Communications Technologies

This course is intended as an introduction to emerging digital communications technologies. While the primary focus will be on digital and mobile technologies and practices (contemporary new media), the course will also consider a range of older media when they were new including print culture, cinema, television, recorded sound, photography, and the telephone.  Students will focus on social technologies, such as, blogs, wikis and social spaces like YouTube, Facebook and Twitter to explore how people find information and how organizations communicate.  3 hrs. lecture/wk.

### WEB 236 Web Apps I

Mobile devices outnumber desktop and laptop computers three to one worldwide. This course will cover practical guidelines, standards, techniques and best practices for building web applications using Client-Side programming including HTML, Cascading Stylesheet and JavaScript, including basic design and development principles for all mobile devices and platforms. Students will have strong knowledge about the methods and tools used in developing web applications. 3 hrs. lecture/wk.

### WEB 238 CMS Development

Content Management Systems (CMS) have gained in popularity as the number of robust and complex websites continues to grow. Students will cover the lifecycle of web sites, including their creation, management, distribution, and publishing of content.  This hands-on course will cover open source CMS applications such as Joomla, Drupal, Wordpress and other technologies and the resources available to designers and developers.  Students will explore the fundamentals of planning dynamic websites, CMS database management, developing CSS-controlled site templates, and creating database-driven websites through the planning and creation of their own topic-based sites. Student exercises include how to interact, engage and contribute to online communities and projects. 3 hrs. lecture/wk.

### WEB 240 HTML and CSS II

This course focuses on the latest generation of browser-based technologies for front-end design and development. Topics in the course include Cascading Style Sheets (CSS), Hypertext Markup Language (HTML) elements, HTML Application Programming Interface (API), forms, audio and video, offline applications, Canvas drawing and animation, communication APIs, Web Sockets and Web Workers, Geolocation, local and session storage, Web Structured Query language (SQL) Database, and advanced topics such as mobile web applications, performance analysis, browser issues, and developer tools.  3 hrs lecture/wk.

### WEB 241 Digital Management Methods

The course covers systems development methodologies that cover the phases of development process from an idea to a product. Students will learn methods and tools that are used in the process of developing web-based and digital media applications. The course will introduce the students to systems development life cycle and the basic skills needed in systems analysis, design, and development. Students will deliver an integrated, strategic campaign that demonstrates innovative digital media mastery. Out-of-class collaboration is required to complete the final project 3 hrs. lecture, 2 hrs. open lab/wk.

### WEB 243 SEO

This course will cover how to optimize a website to maximize search engine ranking.  Upon completion of the course students will be able to identify and implement effective Web site designs and strategies for search engine optimization. 1 hr. lecture/wk.

### WEB 244 Interactive Scripting: jQuery

Designers and developers can use jQuery to have complete access to all CSS styles of any element on a web page, effortless web page content manipulation via filters and patterns, detection or creation of events (mouse movement or click), moving, hiding and fading elements and much more. Students will be exposed to how to write efficient jQuery selectors to round up sets of DOM elements, how to use the framework's many methods to manipulate DOM elements, how to use the jQuery event API to set up event listeners and event delegation, how to manage Ajax requests with jQuery and how to extend jQuery with custom filters and methods. 3hrs Lecture /wk.

### WEB 245 Motion Graphics Tools: After Effects

This course is designed to introduce students to motion graphics and special effects. All basic applications of the program will be touched upon including; credits, transitions, filters, masks, mattes. Students will experience the complete motion graphics workflow, beginning by capturing their own still images and videos and concluding by rendering and exporting an original composition.  1hr. lecture/wk

### WEB 246 Web Apps II

This course examines the theory, concepts, and techniques for designing, producing, and evaluating Web applications to meet specific information needs. Students will engage with concepts, techniques and system issues in advanced web application design and development using advanced programming tools and techniques. Students will look beyond the current status of development and design techniques and conjecture what is possible in the future.  3 hrs. lecture/wk.

### WEB 290 Web Development and Digital Media Capstone

This course is the culmination of the coursework that makes up the Web Development and Digital Media AAS degree. It pulls from each of the core program courses to allow students to walk through the entire Web design process, including design/project documentation, wire framing, creating mock-ups, revisions, pages and final deliverables. Upon completion of course, students will have a professional website that can serve as part of their professional portfolio. 3 hrs. lecture/wk.

**Comment by jccc-dn** [comment]
FYI, I uploaded a copy of the course descriptions as a text file (WDDMCourseDescriptions.txt) to the Google Drive under "Site Content ->>Program" as well so it is found with the other content assets.
