### ISSUE TITLE
Jan Bryan Hunt

### ISSUE THREAD

**Issue by jhopper** [WEB290-2015/webdevcapstone#22]
Please remove the Jan Bryan Hunt reference in the Student Gallery.  Jan is an illustrator, the site shown is not her site.  We cannot re-brand her as this site is doing. We do not have the rights to use her website

**Comment by jccc-dn** [comment]
Your message brings up a good point. The same problem also exists for many of the other student works we are displaying. The class project was a (unauthorized) re-design of an existing web site. Would it be possible to leave these site redesigns up with an explanatory disclaimer added to indicate that the depicted sites have no relation to any actual site and are unauthorized, etc.?

**Comment by jccc-dn** [comment]
Jan Bryan Hunt page and reference on the showcase page has been removed.

**Comment by jhopper** [comment]
In the case of Jan, no.  Her brand is extremely important to her success as an illustrator.  For other instances like this one we need to make sure we have permission from the site owner.
