### ISSUE TITLE
Google Analytics Script - UA-50954802-1

### ISSUE THREAD

**Issue by cnorwood3** [WEB290-2015/webdevcapstone#31]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50954802-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by jccc-dn** [comment]
*Added GA scripts to all 19 individual student works pages
*Added GA scripts to the student resources pages

**Comment by jccc-dn** [comment]
Added GA code to rest of pages yesterday.
