### ISSUE TITLE
Testimonials (renamed Student Stories)

### ISSUE THREAD

**Issue by pmcmahon02** [WEB290-2015/webdevcapstone#34]
#1  Take testimonial feedback and use it to develop the Testimonial page.

**Comment by pmcmahon02** [comment]
Have testimonial page live, only 2 submissions recieved so far.  If any of you would like to participate let me know and I will send you the Q&A.  If not I will add myself, we need at least 3-4 submissions.

**Comment by cnorwood3** [comment]
3 testimonials on Student stories page, added accordian feature to each student's story.
