### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by jhopper** [WEB290-2015/webdevcapstone#39]
##### Does this degree transfer to a 4-year college?
- Yes, but the program is designed to prepare you for work immediately after earning your degree or certificates.

Unfortunately our Wed Development and Digital Media degree **does not** have a transfer option.  We are working on that.  It is unknown when we might have an agreement with a four-year institution.

**Comment by cnorwood3** [comment]
The FAQ answer has been edited and uploaded
